# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Hugo/Documents/GitHub/WAV_Player/05_FPGA/Arty-S7/WAV_Player/WAV_Player.srcs/sources_1/ip/FIFO_32bit/FIFO_32bit.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FIFO_32bit || ORIG_REF_NAME==FIFO_32bit} -quiet] -quiet

# XDC: c:/Users/Hugo/Documents/GitHub/WAV_Player/05_FPGA/Arty-S7/WAV_Player/WAV_Player.srcs/sources_1/ip/FIFO_32bit/FIFO_32bit.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==FIFO_32bit || ORIG_REF_NAME==FIFO_32bit} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/Hugo/Documents/GitHub/WAV_Player/05_FPGA/Arty-S7/WAV_Player/WAV_Player.srcs/sources_1/ip/FIFO_32bit/FIFO_32bit_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==FIFO_32bit || ORIG_REF_NAME==FIFO_32bit} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: new/Audio_Interface_ooc.xdc

# IP: C:/Users/Hugo/Documents/GitHub/WAV_Player/05_FPGA/Arty-S7/WAV_Player/WAV_Player.srcs/sources_1/ip/FIFO_32bit/FIFO_32bit.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FIFO_32bit || ORIG_REF_NAME==FIFO_32bit} -quiet] -quiet

# XDC: c:/Users/Hugo/Documents/GitHub/WAV_Player/05_FPGA/Arty-S7/WAV_Player/WAV_Player.srcs/sources_1/ip/FIFO_32bit/FIFO_32bit.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==FIFO_32bit || ORIG_REF_NAME==FIFO_32bit} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/Hugo/Documents/GitHub/WAV_Player/05_FPGA/Arty-S7/WAV_Player/WAV_Player.srcs/sources_1/ip/FIFO_32bit/FIFO_32bit_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==FIFO_32bit || ORIG_REF_NAME==FIFO_32bit} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: new/Audio_Interface_ooc.xdc
