# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/hugoh/Documents/GitHub/WAV_Player/02_Source/Contraintes_Arty.xdc

# IP: ip/RAM_2048_16bit/RAM_2048_16bit.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RAM_2048_16bit || ORIG_REF_NAME==RAM_2048_16bit} -quiet] -quiet

# XDC: C:/Users/hugoh/Documents/GitHub/WAV_Player/05_FPGA/Arty-S7/WAV_Player/WAV_Player.srcs/VGA_interface/new/VGA_interface_ooc.xdc

# XDC: ip/RAM_2048_16bit/RAM_2048_16bit_ooc.xdc
