# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/hhartmann/Desktop/svn_fpga/trunk/01_Projects/WAV_Player/02_Source/Contraintes_Arty.xdc

# IP: ip/FFT_SQRT/FFT_SQRT.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FFT_SQRT || ORIG_REF_NAME==FFT_SQRT} -quiet] -quiet

# IP: ip/ROM_256_32bit/ROM_256_32bit.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ROM_256_32bit || ORIG_REF_NAME==ROM_256_32bit} -quiet] -quiet

# IP: ip/BRAM_512_32bit/BRAM_512_32bit.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BRAM_512_32bit || ORIG_REF_NAME==BRAM_512_32bit} -quiet] -quiet

# IP: ip/BRAM_512_16bit/BRAM_512_16bit.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BRAM_512_16bit || ORIG_REF_NAME==BRAM_512_16bit} -quiet] -quiet

# IP: ip/ROM_32_16bit/ROM_32_16bit.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ROM_32_16bit || ORIG_REF_NAME==ROM_32_16bit} -quiet] -quiet

# IP: ip/ROM_1024_16bit_4/ROM_1024_16bit_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ROM_1024_16bit_4 || ORIG_REF_NAME==ROM_1024_16bit_4} -quiet] -quiet

# IP: ip/ROM_1024_16bit_3/ROM_1024_16bit_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ROM_1024_16bit_3 || ORIG_REF_NAME==ROM_1024_16bit_3} -quiet] -quiet

# IP: ip/ROM_1024_16bit_2/ROM_1024_16bit_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ROM_1024_16bit_2 || ORIG_REF_NAME==ROM_1024_16bit_2} -quiet] -quiet

# IP: ip/ROM_1024_16bit_1/ROM_1024_16bit_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ROM_1024_16bit_1 || ORIG_REF_NAME==ROM_1024_16bit_1} -quiet] -quiet

# IP: ip/ROM_1024_16bit_0/ROM_1024_16bit_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ROM_1024_16bit_0 || ORIG_REF_NAME==ROM_1024_16bit_0} -quiet] -quiet

# IP: ip/ROM_1024_16bit_5/ROM_1024_16bit_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ROM_1024_16bit_5 || ORIG_REF_NAME==ROM_1024_16bit_5} -quiet] -quiet

# IP: ip/RAM_2048_8bit/RAM_2048_8bit.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RAM_2048_8bit || ORIG_REF_NAME==RAM_2048_8bit} -quiet] -quiet

# IP: ip/RAM_22050_8bit/RAM_22050_8bit.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RAM_22050_8bit || ORIG_REF_NAME==RAM_22050_8bit} -quiet] -quiet

# XDC: ip/ROM_256_32bit/ROM_256_32bit_ooc.xdc

# XDC: ip/BRAM_512_32bit/BRAM_512_32bit_ooc.xdc

# XDC: ip/BRAM_512_16bit/BRAM_512_16bit_ooc.xdc

# XDC: ip/ROM_32_16bit/ROM_32_16bit_ooc.xdc

# XDC: ip/ROM_1024_16bit_4/ROM_1024_16bit_4_ooc.xdc

# XDC: ip/ROM_1024_16bit_3/ROM_1024_16bit_3_ooc.xdc

# XDC: ip/ROM_1024_16bit_2/ROM_1024_16bit_2_ooc.xdc

# XDC: ip/ROM_1024_16bit_1/ROM_1024_16bit_1_ooc.xdc

# XDC: ip/ROM_1024_16bit_0/ROM_1024_16bit_0_ooc.xdc

# XDC: ip/ROM_1024_16bit_5/ROM_1024_16bit_5_ooc.xdc

# XDC: ip/RAM_2048_8bit/RAM_2048_8bit_ooc.xdc

# XDC: ip/RAM_22050_8bit/RAM_22050_8bit_ooc.xdc
