# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Hugo/Documents/GitHub/WAV_Player/05_FPGA/Arty-S7/WAV_Player/WAV_Player.srcs/sources_1/ip/Multiplier_u16_s16/Multiplier_u16_s16.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Multiplier_u16_s16 || ORIG_REF_NAME==Multiplier_u16_s16} -quiet] -quiet

# IP: C:/Users/Hugo/Documents/GitHub/WAV_Player/05_FPGA/Arty-S7/WAV_Player/WAV_Player.srcs/sources_1/ip/ROM_32_16bit/ROM_32_16bit.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ROM_32_16bit || ORIG_REF_NAME==ROM_32_16bit} -quiet] -quiet

# XDC: c:/Users/Hugo/Documents/GitHub/WAV_Player/05_FPGA/Arty-S7/WAV_Player/WAV_Player.srcs/sources_1/ip/ROM_32_16bit/ROM_32_16bit_ooc.xdc

# XDC: new/EQ_stage_ooc.xdc

# IP: C:/Users/Hugo/Documents/GitHub/WAV_Player/05_FPGA/Arty-S7/WAV_Player/WAV_Player.srcs/sources_1/ip/Multiplier_u16_s16/Multiplier_u16_s16.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Multiplier_u16_s16 || ORIG_REF_NAME==Multiplier_u16_s16} -quiet] -quiet

# IP: C:/Users/Hugo/Documents/GitHub/WAV_Player/05_FPGA/Arty-S7/WAV_Player/WAV_Player.srcs/sources_1/ip/ROM_32_16bit/ROM_32_16bit.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ROM_32_16bit || ORIG_REF_NAME==ROM_32_16bit} -quiet] -quiet

# XDC: c:/Users/Hugo/Documents/GitHub/WAV_Player/05_FPGA/Arty-S7/WAV_Player/WAV_Player.srcs/sources_1/ip/ROM_32_16bit/ROM_32_16bit_ooc.xdc

# XDC: new/EQ_stage_ooc.xdc
