# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Hugo/Documents/GitHub/WAV_Player/05_FPGA/Arty-S7/WAV_Player/WAV_Player.srcs/sources_1/ip/NRM_SQRT/NRM_SQRT.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==NRM_SQRT || ORIG_REF_NAME==NRM_SQRT} -quiet] -quiet

# IP: C:/Users/Hugo/Documents/GitHub/WAV_Player/05_FPGA/Arty-S7/WAV_Player/WAV_Player.srcs/sources_1/ip/Multiplier_s16_s16/Multiplier_s16_s16.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Multiplier_s16_s16 || ORIG_REF_NAME==Multiplier_s16_s16} -quiet] -quiet

# IP: C:/Users/Hugo/Documents/GitHub/WAV_Player/05_FPGA/Arty-S7/WAV_Player/WAV_Player.srcs/sources_1/ip/BRAM_2048_32bit/BRAM_2048_32bit.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BRAM_2048_32bit || ORIG_REF_NAME==BRAM_2048_32bit} -quiet] -quiet

# XDC: c:/Users/Hugo/Documents/GitHub/WAV_Player/05_FPGA/Arty-S7/WAV_Player/WAV_Player.srcs/sources_1/ip/BRAM_2048_32bit/BRAM_2048_32bit_ooc.xdc

# XDC: new/NRM_Wrapper_ooc.xdc

# IP: C:/Users/Hugo/Documents/GitHub/WAV_Player/05_FPGA/Arty-S7/WAV_Player/WAV_Player.srcs/sources_1/ip/NRM_SQRT/NRM_SQRT.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==NRM_SQRT || ORIG_REF_NAME==NRM_SQRT} -quiet] -quiet

# IP: C:/Users/Hugo/Documents/GitHub/WAV_Player/05_FPGA/Arty-S7/WAV_Player/WAV_Player.srcs/sources_1/ip/Multiplier_s16_s16/Multiplier_s16_s16.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Multiplier_s16_s16 || ORIG_REF_NAME==Multiplier_s16_s16} -quiet] -quiet

# IP: C:/Users/Hugo/Documents/GitHub/WAV_Player/05_FPGA/Arty-S7/WAV_Player/WAV_Player.srcs/sources_1/ip/BRAM_2048_32bit/BRAM_2048_32bit.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BRAM_2048_32bit || ORIG_REF_NAME==BRAM_2048_32bit} -quiet] -quiet

# XDC: c:/Users/Hugo/Documents/GitHub/WAV_Player/05_FPGA/Arty-S7/WAV_Player/WAV_Player.srcs/sources_1/ip/BRAM_2048_32bit/BRAM_2048_32bit_ooc.xdc

# XDC: new/NRM_Wrapper_ooc.xdc
