# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: C:/Users/hhartmann/Desktop/svn_fpga/trunk/01_Projects/WAV_Player/05_FPGA/Arty-S7/WAV_Player/WAV_Player.srcs/sources_1/bd/FFT_512/FFT_512.bd
# Block Designs: The module: 'FFT_512' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/Users/hhartmann/Desktop/svn_fpga/trunk/01_Projects/WAV_Player/05_FPGA/Arty-S7/WAV_Player/WAV_Player.srcs/sources_1/bd/FFT_512/ip/FFT_512_FFT_Wrapper_0_0/FFT_512_FFT_Wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FFT_512_FFT_Wrapper_0_0 || ORIG_REF_NAME==FFT_512_FFT_Wrapper_0_0} -quiet] -quiet

# IP: C:/Users/hhartmann/Desktop/svn_fpga/trunk/01_Projects/WAV_Player/05_FPGA/Arty-S7/WAV_Player/WAV_Player.srcs/sources_1/ip/FFT_SQRT/FFT_SQRT.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FFT_SQRT || ORIG_REF_NAME==FFT_SQRT} -quiet] -quiet

# IP: C:/Users/hhartmann/Desktop/svn_fpga/trunk/01_Projects/WAV_Player/05_FPGA/Arty-S7/WAV_Player/WAV_Player.srcs/sources_1/ip/ROM_256_32bit/ROM_256_32bit.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ROM_256_32bit || ORIG_REF_NAME==ROM_256_32bit} -quiet] -quiet

# IP: C:/Users/hhartmann/Desktop/svn_fpga/trunk/01_Projects/WAV_Player/05_FPGA/Arty-S7/WAV_Player/WAV_Player.srcs/sources_1/ip/BRAM_512_32bit/BRAM_512_32bit.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BRAM_512_32bit || ORIG_REF_NAME==BRAM_512_32bit} -quiet] -quiet

# IP: C:/Users/hhartmann/Desktop/svn_fpga/trunk/01_Projects/WAV_Player/05_FPGA/Arty-S7/WAV_Player/WAV_Player.srcs/sources_1/ip/BRAM_512_16bit/BRAM_512_16bit.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BRAM_512_16bit || ORIG_REF_NAME==BRAM_512_16bit} -quiet] -quiet

# XDC: c:/Users/hhartmann/Desktop/svn_fpga/trunk/01_Projects/WAV_Player/05_FPGA/Arty-S7/WAV_Player/WAV_Player.srcs/sources_1/ip/ROM_256_32bit/ROM_256_32bit_ooc.xdc

# XDC: c:/Users/hhartmann/Desktop/svn_fpga/trunk/01_Projects/WAV_Player/05_FPGA/Arty-S7/WAV_Player/WAV_Player.srcs/sources_1/ip/BRAM_512_32bit/BRAM_512_32bit_ooc.xdc

# XDC: c:/Users/hhartmann/Desktop/svn_fpga/trunk/01_Projects/WAV_Player/05_FPGA/Arty-S7/WAV_Player/WAV_Player.srcs/sources_1/ip/BRAM_512_16bit/BRAM_512_16bit_ooc.xdc

# XDC: C:/Users/hhartmann/Desktop/svn_fpga/trunk/01_Projects/WAV_Player/05_FPGA/Arty-S7/WAV_Player/WAV_Player.srcs/sources_1/bd/FFT_512/FFT_512_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FFT_512'. Do not add the DONT_TOUCH constraint.

# Block Designs: C:/Users/hhartmann/Desktop/svn_fpga/trunk/01_Projects/WAV_Player/05_FPGA/Arty-S7/WAV_Player/WAV_Player.srcs/sources_1/bd/FFT_512/FFT_512.bd
# Block Designs: The module: 'FFT_512' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/Users/hhartmann/Desktop/svn_fpga/trunk/01_Projects/WAV_Player/05_FPGA/Arty-S7/WAV_Player/WAV_Player.srcs/sources_1/bd/FFT_512/ip/FFT_512_FFT_Wrapper_0_0/FFT_512_FFT_Wrapper_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FFT_512_FFT_Wrapper_0_0 || ORIG_REF_NAME==FFT_512_FFT_Wrapper_0_0} -quiet] -quiet

# IP: C:/Users/hhartmann/Desktop/svn_fpga/trunk/01_Projects/WAV_Player/05_FPGA/Arty-S7/WAV_Player/WAV_Player.srcs/sources_1/ip/FFT_SQRT/FFT_SQRT.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FFT_SQRT || ORIG_REF_NAME==FFT_SQRT} -quiet] -quiet

# IP: C:/Users/hhartmann/Desktop/svn_fpga/trunk/01_Projects/WAV_Player/05_FPGA/Arty-S7/WAV_Player/WAV_Player.srcs/sources_1/ip/ROM_256_32bit/ROM_256_32bit.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ROM_256_32bit || ORIG_REF_NAME==ROM_256_32bit} -quiet] -quiet

# IP: C:/Users/hhartmann/Desktop/svn_fpga/trunk/01_Projects/WAV_Player/05_FPGA/Arty-S7/WAV_Player/WAV_Player.srcs/sources_1/ip/BRAM_512_32bit/BRAM_512_32bit.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BRAM_512_32bit || ORIG_REF_NAME==BRAM_512_32bit} -quiet] -quiet

# IP: C:/Users/hhartmann/Desktop/svn_fpga/trunk/01_Projects/WAV_Player/05_FPGA/Arty-S7/WAV_Player/WAV_Player.srcs/sources_1/ip/BRAM_512_16bit/BRAM_512_16bit.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BRAM_512_16bit || ORIG_REF_NAME==BRAM_512_16bit} -quiet] -quiet

# XDC: c:/Users/hhartmann/Desktop/svn_fpga/trunk/01_Projects/WAV_Player/05_FPGA/Arty-S7/WAV_Player/WAV_Player.srcs/sources_1/ip/ROM_256_32bit/ROM_256_32bit_ooc.xdc

# XDC: c:/Users/hhartmann/Desktop/svn_fpga/trunk/01_Projects/WAV_Player/05_FPGA/Arty-S7/WAV_Player/WAV_Player.srcs/sources_1/ip/BRAM_512_32bit/BRAM_512_32bit_ooc.xdc

# XDC: c:/Users/hhartmann/Desktop/svn_fpga/trunk/01_Projects/WAV_Player/05_FPGA/Arty-S7/WAV_Player/WAV_Player.srcs/sources_1/ip/BRAM_512_16bit/BRAM_512_16bit_ooc.xdc

# XDC: C:/Users/hhartmann/Desktop/svn_fpga/trunk/01_Projects/WAV_Player/05_FPGA/Arty-S7/WAV_Player/WAV_Player.srcs/sources_1/bd/FFT_512/FFT_512_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FFT_512'. Do not add the DONT_TOUCH constraint.
