set_property SRC_FILE_INFO {cfile:C:/Users/hugoh/Documents/GitHub/WAV_Player/02_Source/Contraintes_Arty.xdc rfile:../../../../../../02_Source/Contraintes_Arty.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN F14   IOSTANDARD LVCMOS33 } [get_ports { CLK12MHZ }]; #IO_L13P_T2_MRCC_15 Sch=uclk
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN H14   IOSTANDARD LVCMOS33 } [get_ports { SW[0] }]; #IO_L20N_T3_A19_15 Sch=sw[0]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN H18   IOSTANDARD LVCMOS33 } [get_ports { SW[1] }]; #IO_L21P_T3_DQS_15 Sch=sw[1]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN G18   IOSTANDARD LVCMOS33 } [get_ports { SW[2] }]; #IO_L21N_T3_DQS_A18_15 Sch=sw[2]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN M5    IOSTANDARD SSTL135 } [get_ports { SW[3] }]; #IO_L6N_T0_VREF_34 Sch=sw[3]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN E18   IOSTANDARD LVCMOS33 } [get_ports { LED0 }]; #IO_L16N_T2_A27_15 Sch=led[2]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN G15   IOSTANDARD LVCMOS33 } [get_ports { RESET }]; #IO_L18N_T2_A23_15 Sch=btn[0]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN J16   IOSTANDARD LVCMOS33 } [get_ports { VOL_DOWN }]; #IO_L19N_T3_A21_VREF_15 Sch=btn[2]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN H13   IOSTANDARD LVCMOS33 } [get_ports { VOL_UP }]; #IO_L20P_T3_A20_15 Sch=btn[3]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN L17   IOSTANDARD LVCMOS33 } [get_ports { RED_OUT[0] }]; #IO_L4P_T0_D04_14 Sch=ja_p[1]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN L18   IOSTANDARD LVCMOS33 } [get_ports { RED_OUT[1] }]; #IO_L4N_T0_D05_14 Sch=ja_n[1]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN M14   IOSTANDARD LVCMOS33 } [get_ports { RED_OUT[2] }]; #IO_L5P_T0_D06_14 Sch=ja_p[2]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN N14   IOSTANDARD LVCMOS33 } [get_ports { RED_OUT[3] }]; #IO_L5N_T0_D07_14 Sch=ja_n[2]
set_property src_info {type:XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN M16   IOSTANDARD LVCMOS33 } [get_ports { BLUE_OUT[0] }]; #IO_L7P_T1_D09_14 Sch=ja_p[3]
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN M17   IOSTANDARD LVCMOS33 } [get_ports { BLUE_OUT[1] }]; #IO_L7N_T1_D10_14 Sch=ja_n[3]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN M18   IOSTANDARD LVCMOS33 } [get_ports { BLUE_OUT[2] }]; #IO_L8P_T1_D11_14 Sch=ja_p[4]
set_property src_info {type:XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN N18   IOSTANDARD LVCMOS33 } [get_ports { BLUE_OUT[3] }]; #IO_L8N_T1_D12_14 Sch=ja_n[4]
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN P17   IOSTANDARD LVCMOS33 } [get_ports { GREEN_OUT[0] }]; #IO_L9P_T1_DQS_14 Sch=jb_p[1]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN P18   IOSTANDARD LVCMOS33 } [get_ports { GREEN_OUT[1] }]; #IO_L9N_T1_DQS_D13_14 Sch=jb_n[1]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN R18   IOSTANDARD LVCMOS33 } [get_ports { GREEN_OUT[2] }]; #IO_L10P_T1_D14_14 Sch=jb_p[2]
set_property src_info {type:XDC file:1 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN T18   IOSTANDARD LVCMOS33 } [get_ports { GREEN_OUT[3] }]; #IO_L10N_T1_D15_14 Sch=jb_n[2]
set_property src_info {type:XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN P14   IOSTANDARD LVCMOS33 } [get_ports { HSYNC_OUT }]; #IO_L11P_T1_SRCC_14 Sch=jb_p[3]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN P15   IOSTANDARD LVCMOS33 } [get_ports { VSYNC_OUT }]; #IO_L11N_T1_SRCC_14 Sch=jb_n[3]
set_property src_info {type:XDC file:1 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN V15   IOSTANDARD LVCMOS33 } [get_ports { MCLK_OUT }]; #IO_L20N_T3_A07_D23_14 Sch=jd1/ck_io[33]
set_property src_info {type:XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN U12   IOSTANDARD LVCMOS33 } [get_ports { LRCK_OUT }]; #IO_L21P_T3_DQS_14 Sch=jd2/ck_io[32]
set_property src_info {type:XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN V13   IOSTANDARD LVCMOS33 } [get_ports { SCLK_OUT }]; #IO_L21N_T3_DQS_A06_D22_14 Sch=jd3/ck_io[31]
set_property src_info {type:XDC file:1 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN T12   IOSTANDARD LVCMOS33 } [get_ports { DOUT }]; #IO_L22P_T3_A05_D21_14 Sch=jd4/ck_io[30]
set_property src_info {type:XDC file:1 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN T13   IOSTANDARD LVCMOS33 } [get_ports { MCLK_IN }]; #IO_L22N_T3_A04_D20_14 Sch=jd7/ck_io[29]
set_property src_info {type:XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN R11   IOSTANDARD LVCMOS33 } [get_ports { LRCK_IN }]; #IO_L23P_T3_A03_D19_14 Sch=jd8/ck_io[28]
set_property src_info {type:XDC file:1 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN T11   IOSTANDARD LVCMOS33 } [get_ports { SCLK_IN }]; #IO_L23N_T3_A02_D18_14 Sch=jd9/ck_io[27]
set_property src_info {type:XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN U11   IOSTANDARD LVCMOS33 } [get_ports { DIN }]; #IO_L24P_T3_A01_D17_14 Sch=jd10/ck_io[26]
set_property src_info {type:XDC file:1 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN R12   IOSTANDARD LVCMOS33 } [get_ports { TX }]; #IO_25_14 Sch=uart_rxd_out
set_property src_info {type:XDC file:1 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN V12   IOSTANDARD LVCMOS33 } [get_ports { RX }]; #IO_L24N_T3_A00_D16_14 Sch=uart_txd_in
set_property src_info {type:XDC file:1 line:194 export:INPUT save:INPUT read:READ} [current_design]
set_multicycle_path -hold -from [get_pins {{U_VGA_controller/h_addr_counter_reg[0]/C} {U_VGA_controller/h_addr_counter_reg[1]/C} {U_VGA_controller/h_addr_counter_reg[2]/C} {U_VGA_controller/h_addr_counter_reg[3]/C} {U_VGA_controller/h_addr_counter_reg[4]/C} {U_VGA_controller/h_addr_counter_reg[5]/C} {U_VGA_controller/h_addr_counter_reg[6]/C} {U_VGA_controller/h_addr_counter_reg[7]/C} {U_VGA_controller/h_addr_counter_reg[8]/C} {U_VGA_controller/h_addr_counter_reg[9]/C} {U_VGA_controller/h_addr_counter_reg[10]/C} {U_VGA_controller/h_addr_counter_reg[11]/C} {U_VGA_controller/h_addr_counter_reg[12]/C} {U_VGA_controller/h_addr_counter_reg[13]/C} {U_VGA_controller/h_addr_counter_reg[14]/C} {U_VGA_controller/h_addr_counter_reg[15]/C}}] -to [get_pins -hierarchical -filter { NAME =~  "*U_NRM_RAM*" && NAME =~  "*ADDRARDADDR*" }] 2
set_property src_info {type:XDC file:1 line:195 export:INPUT save:INPUT read:READ} [current_design]
set_multicycle_path -setup -from [get_pins {{U_VGA_controller/h_addr_counter_reg[0]/C} {U_VGA_controller/h_addr_counter_reg[1]/C} {U_VGA_controller/h_addr_counter_reg[2]/C} {U_VGA_controller/h_addr_counter_reg[3]/C} {U_VGA_controller/h_addr_counter_reg[4]/C} {U_VGA_controller/h_addr_counter_reg[5]/C} {U_VGA_controller/h_addr_counter_reg[6]/C} {U_VGA_controller/h_addr_counter_reg[7]/C} {U_VGA_controller/h_addr_counter_reg[8]/C} {U_VGA_controller/h_addr_counter_reg[9]/C} {U_VGA_controller/h_addr_counter_reg[10]/C} {U_VGA_controller/h_addr_counter_reg[11]/C} {U_VGA_controller/h_addr_counter_reg[12]/C} {U_VGA_controller/h_addr_counter_reg[13]/C} {U_VGA_controller/h_addr_counter_reg[14]/C} {U_VGA_controller/h_addr_counter_reg[15]/C}}] -to [get_pins -hierarchical -filter { NAME =~  "*U_NRM_RAM*" && NAME =~  "*ADDRARDADDR*" }] 2
