# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: C:/Users/hhartmann/Desktop/svn_fpga/trunk/01_Projects/WAV_Player/05_FPGA/Arty-S7/WAV_Player/WAV_Player.srcs/sources_1/bd/EQ/EQ.bd
# Block Designs: The module: 'EQ' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/Users/hhartmann/Desktop/svn_fpga/trunk/01_Projects/WAV_Player/05_FPGA/Arty-S7/WAV_Player/WAV_Player.srcs/sources_1/bd/EQ/ip/EQ_EQ_stage_0_0/EQ_EQ_stage_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EQ_EQ_stage_0_0 || ORIG_REF_NAME==EQ_EQ_stage_0_0} -quiet] -quiet

# IP: C:/Users/hhartmann/Desktop/svn_fpga/trunk/01_Projects/WAV_Player/05_FPGA/Arty-S7/WAV_Player/WAV_Player.srcs/sources_1/ip/ROM_32_16bit/ROM_32_16bit.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ROM_32_16bit || ORIG_REF_NAME==ROM_32_16bit} -quiet] -quiet

# XDC: c:/Users/hhartmann/Desktop/svn_fpga/trunk/01_Projects/WAV_Player/05_FPGA/Arty-S7/WAV_Player/WAV_Player.srcs/sources_1/ip/ROM_32_16bit/ROM_32_16bit_ooc.xdc

# XDC: C:/Users/hhartmann/Desktop/svn_fpga/trunk/01_Projects/WAV_Player/05_FPGA/Arty-S7/WAV_Player/WAV_Player.srcs/sources_1/bd/EQ/EQ_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'EQ'. Do not add the DONT_TOUCH constraint.

# Block Designs: C:/Users/hhartmann/Desktop/svn_fpga/trunk/01_Projects/WAV_Player/05_FPGA/Arty-S7/WAV_Player/WAV_Player.srcs/sources_1/bd/EQ/EQ.bd
# Block Designs: The module: 'EQ' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/Users/hhartmann/Desktop/svn_fpga/trunk/01_Projects/WAV_Player/05_FPGA/Arty-S7/WAV_Player/WAV_Player.srcs/sources_1/bd/EQ/ip/EQ_EQ_stage_0_0/EQ_EQ_stage_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EQ_EQ_stage_0_0 || ORIG_REF_NAME==EQ_EQ_stage_0_0} -quiet] -quiet

# IP: C:/Users/hhartmann/Desktop/svn_fpga/trunk/01_Projects/WAV_Player/05_FPGA/Arty-S7/WAV_Player/WAV_Player.srcs/sources_1/ip/ROM_32_16bit/ROM_32_16bit.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ROM_32_16bit || ORIG_REF_NAME==ROM_32_16bit} -quiet] -quiet

# XDC: c:/Users/hhartmann/Desktop/svn_fpga/trunk/01_Projects/WAV_Player/05_FPGA/Arty-S7/WAV_Player/WAV_Player.srcs/sources_1/ip/ROM_32_16bit/ROM_32_16bit_ooc.xdc

# XDC: C:/Users/hhartmann/Desktop/svn_fpga/trunk/01_Projects/WAV_Player/05_FPGA/Arty-S7/WAV_Player/WAV_Player.srcs/sources_1/bd/EQ/EQ_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'EQ'. Do not add the DONT_TOUCH constraint.
