# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/hhartmann/Desktop/svn_fpga/trunk/01_Projects/WAV_Player/05_FPGA/Arty-S7/WAV_Player/WAV_Player.srcs/sources_1/ip/RAM_22050_8bit/RAM_22050_8bit.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RAM_22050_8bit || ORIG_REF_NAME==RAM_22050_8bit} -quiet] -quiet

# XDC: c:/Users/hhartmann/Desktop/svn_fpga/trunk/01_Projects/WAV_Player/05_FPGA/Arty-S7/WAV_Player/WAV_Player.srcs/sources_1/ip/RAM_22050_8bit/RAM_22050_8bit_ooc.xdc

# IP: C:/Users/hhartmann/Desktop/svn_fpga/trunk/01_Projects/WAV_Player/05_FPGA/Arty-S7/WAV_Player/WAV_Player.srcs/sources_1/ip/RAM_22050_8bit/RAM_22050_8bit.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RAM_22050_8bit || ORIG_REF_NAME==RAM_22050_8bit} -quiet] -quiet

# XDC: c:/Users/hhartmann/Desktop/svn_fpga/trunk/01_Projects/WAV_Player/05_FPGA/Arty-S7/WAV_Player/WAV_Player.srcs/sources_1/ip/RAM_22050_8bit/RAM_22050_8bit_ooc.xdc
