# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Hugo/Documents/GitHub/WAV_Player/05_FPGA/Arty-S7/WAV_Player/WAV_Player.srcs/sources_1/ip/FIFO_16bit_1024/FIFO_16bit_1024.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FIFO_16bit_1024 || ORIG_REF_NAME==FIFO_16bit_1024} -quiet] -quiet

# IP: C:/Users/Hugo/Documents/GitHub/WAV_Player/05_FPGA/Arty-S7/WAV_Player/WAV_Player.srcs/sources_1/ip/FIFO_8bit_2048/FIFO_8bit_2048.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FIFO_8bit_2048 || ORIG_REF_NAME==FIFO_8bit_2048} -quiet] -quiet

# XDC: c:/Users/Hugo/Documents/GitHub/WAV_Player/05_FPGA/Arty-S7/WAV_Player/WAV_Player.srcs/sources_1/ip/FIFO_16bit_1024/FIFO_16bit_1024.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==FIFO_16bit_1024 || ORIG_REF_NAME==FIFO_16bit_1024} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/Hugo/Documents/GitHub/WAV_Player/05_FPGA/Arty-S7/WAV_Player/WAV_Player.srcs/sources_1/ip/FIFO_16bit_1024/FIFO_16bit_1024_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==FIFO_16bit_1024 || ORIG_REF_NAME==FIFO_16bit_1024} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/Hugo/Documents/GitHub/WAV_Player/05_FPGA/Arty-S7/WAV_Player/WAV_Player.srcs/sources_1/ip/FIFO_8bit_2048/FIFO_8bit_2048.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==FIFO_8bit_2048 || ORIG_REF_NAME==FIFO_8bit_2048} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/Hugo/Documents/GitHub/WAV_Player/05_FPGA/Arty-S7/WAV_Player/WAV_Player.srcs/sources_1/ip/FIFO_8bit_2048/FIFO_8bit_2048_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==FIFO_8bit_2048 || ORIG_REF_NAME==FIFO_8bit_2048} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: new/PSH_Driver_ooc.xdc

# IP: C:/Users/Hugo/Documents/GitHub/WAV_Player/05_FPGA/Arty-S7/WAV_Player/WAV_Player.srcs/sources_1/ip/FIFO_16bit_1024/FIFO_16bit_1024.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FIFO_16bit_1024 || ORIG_REF_NAME==FIFO_16bit_1024} -quiet] -quiet

# IP: C:/Users/Hugo/Documents/GitHub/WAV_Player/05_FPGA/Arty-S7/WAV_Player/WAV_Player.srcs/sources_1/ip/FIFO_8bit_2048/FIFO_8bit_2048.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FIFO_8bit_2048 || ORIG_REF_NAME==FIFO_8bit_2048} -quiet] -quiet

# XDC: c:/Users/Hugo/Documents/GitHub/WAV_Player/05_FPGA/Arty-S7/WAV_Player/WAV_Player.srcs/sources_1/ip/FIFO_16bit_1024/FIFO_16bit_1024.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==FIFO_16bit_1024 || ORIG_REF_NAME==FIFO_16bit_1024} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/Hugo/Documents/GitHub/WAV_Player/05_FPGA/Arty-S7/WAV_Player/WAV_Player.srcs/sources_1/ip/FIFO_16bit_1024/FIFO_16bit_1024_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==FIFO_16bit_1024 || ORIG_REF_NAME==FIFO_16bit_1024} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/Hugo/Documents/GitHub/WAV_Player/05_FPGA/Arty-S7/WAV_Player/WAV_Player.srcs/sources_1/ip/FIFO_8bit_2048/FIFO_8bit_2048.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==FIFO_8bit_2048 || ORIG_REF_NAME==FIFO_8bit_2048} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/Hugo/Documents/GitHub/WAV_Player/05_FPGA/Arty-S7/WAV_Player/WAV_Player.srcs/sources_1/ip/FIFO_8bit_2048/FIFO_8bit_2048_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==FIFO_8bit_2048 || ORIG_REF_NAME==FIFO_8bit_2048} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: new/PSH_Driver_ooc.xdc
