# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/hugoh/Documents/GitHub/WAV_Player/05_FPGA/Arty-S7/WAV_Player/WAV_Player.srcs/sources_1/ip/RAM_4096_8bit/RAM_4096_8bit.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RAM_4096_8bit || ORIG_REF_NAME==RAM_4096_8bit} -quiet] -quiet

# IP: C:/Users/hugoh/Documents/GitHub/WAV_Player/05_FPGA/Arty-S7/WAV_Player/WAV_Player.srcs/sources_1/ip/Accu_u20/Accu_u20.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Accu_u20 || ORIG_REF_NAME==Accu_u20} -quiet] -quiet

# XDC: c:/Users/hugoh/Documents/GitHub/WAV_Player/05_FPGA/Arty-S7/WAV_Player/WAV_Player.srcs/sources_1/ip/RAM_4096_8bit/RAM_4096_8bit_ooc.xdc

# XDC: new/VU_metre_ooc.xdc

# IP: C:/Users/hugoh/Documents/GitHub/WAV_Player/05_FPGA/Arty-S7/WAV_Player/WAV_Player.srcs/sources_1/ip/RAM_4096_8bit/RAM_4096_8bit.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RAM_4096_8bit || ORIG_REF_NAME==RAM_4096_8bit} -quiet] -quiet

# IP: C:/Users/hugoh/Documents/GitHub/WAV_Player/05_FPGA/Arty-S7/WAV_Player/WAV_Player.srcs/sources_1/ip/Accu_u20/Accu_u20.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Accu_u20 || ORIG_REF_NAME==Accu_u20} -quiet] -quiet

# XDC: c:/Users/hugoh/Documents/GitHub/WAV_Player/05_FPGA/Arty-S7/WAV_Player/WAV_Player.srcs/sources_1/ip/RAM_4096_8bit/RAM_4096_8bit_ooc.xdc

# XDC: new/VU_metre_ooc.xdc
